#!/bin/bash

# $1: extension id

# Upgrade miproxy binary
MIPROXY_VERSION=1.0.2
ARCH=$(uname -m)
if [ "$ARCH" = "x86_64" ]; then
    ARCH_NAME="x86_64"
elif [ "$ARCH" = "aarch64" ]; then
    ARCH_NAME="arm64"
else
    ARCH_NAME="$ARCH"
fi

# Stop old version
pkill -f miproxy || true

# Download new version
curl -L -o app/server/${ARCH_NAME}/miproxy "https://github.com/56025192/miproxy-fpk/releases/download/v${MIPROXY_VERSION}/miproxy_${MIPROXY_VERSION}_linux_${ARCH_NAME}"
chmod +x app/server/${ARCH_NAME}/miproxy
